### ISSUE TITLE
(Feature request) Compatibility with MiSTer BGM?

### ISSUE THREAD

**Issue by felleg** [mrchrisster/MiSTer_SAM#120]
A new script was created ([MiSTer BGM](https://github.com/wizzomafizzo/MiSTer_BGM)) that allows playing music in the main menu of MiSTer. I was wondering if for MiSTer SAM it would be possible to run SAM with MiSTer BGM audio instead (or over?) the cores' audio.

In my opinion, this would make the "screensaver" aspect of SAM even more soothing, or rockin', depending on the intended mood.

**Comment by mrchrisster** [comment]
Unfortunately afaik we don't have control over the core's audio from the Linux side. This would be great I hear you. If somebody knows how to control audio from Linux, I'd love to hear it!

**Comment by seascape** [comment]
MiSTer BGM script can play while cores are loaded, right? (I've not tried this.) If yes and you do that, and reduce the core-specific volume level, is the MiSTer BGM volume affected too? I suspect it is, but if not, then you could have MiSTer BGM at listenable volume while the core volume is zeroed. Could do that for all cores you want to have MiSTer SAM + MiSTer BGM work together on.

Again though, I suspect MiSTer BGM's volume will get zeroed too.

**Comment by mrchrisster** [comment]
How do you reduce core specific volume level from shell? Even if it doesn't play nicely with BGM it would be great to have no sounds playing while SAM is active.

**Comment by seascape** [comment]
I'm referring to the "core volume" level control that is in the left-most menu screen of any loaded core. Below it is "global volume".

**Comment by mrchrisster** [comment]
I understand. SAM would need to be able to control volume though.

**Comment by mrchrisster** [comment]
Your comment got me thinking. I just pushed a new feature to SAM, which mutes global volume while SAM is active. Please reset and update (to pull a fresh ini) and report any issues. If this works than the next step could be to integrate BGM.

**Comment by mrchrisster** [comment]
Getting close to a release for this

**Comment by mrchrisster** [comment]
BGM support is now implemented. You can update and then enable it in the menu "Background Music Player"

**Comment by felleg** [comment]
Thanks! I tried it this morning. I love where this is going, but I have 1 major issue.

The script correctly does everything, including downloading 80s.pls, muting the core, etc. but for some reason the music is not playing while SAM is running. The core is correctly muted, however, and I hear my music upon rebooting the MiSTer. As soon as SAM launches a core, what I get is silence (and the core's sound at very low volume).

**Comment by felleg** [comment]
I just noticed this error log when I run MiST_SAM_on.sh to enable bgm mode:
```
 BGM script is installed already. Continuing with setup.
 Resetting BGM
 Updating MiSTer_SAM.ini to use Mute=Core
Traceback (most recent call last):
  File "/media/fat/Scripts/bgm.sh", line 766, in <module>
    display_gui()
  File "/media/fat/Scripts/bgm.sh", line 644, in display_gui
    status = get_status()
  File "/media/fat/Scripts/bgm.sh", line 549, in get_status
    return send_socket("status").split("\t")
AttributeError: 'NoneType' object has no attribute 'split'
 Downloading from https://github.com/mrchrisster/MiSTer_SAM/blob/main/Media/80s.pls to /media/fat/music/... Done!
 All Done. Starting SAM now.
 Stopping other running instances of MiSTer_SAM_on.sh... Done!
 Starting SAM in the background.
```

**Comment by felleg** [comment]
> Maybe it's an older version? Can you try the disable BGM option and then try the enable again?

Actually, I did `mv /media/fat/Scripts/bgm* /root/junk/` and enabled bgm to make sure this wasn't the case, and that's when the error happened the first time

> Unfortunately it's a limitation of MiSTer that you can't fully mute a core, you can just turn the volume low. I hope this will change in future versions of MiSTer main. I'll put in a feature request.

Honestly, I think I would prefer that than full mute! It would let some characteristic sound effects bleed through, and I think that could potentially be very interesting.

**Comment by mrchrisster** [comment]
Strange, I'm now getting similar error messages after a reboot. Let me look into it and thanks for testing!

**Comment by mrchrisster** [comment]
Looks like there is a bug in bgm.sh if startup is set to no but i was able to work around it. Just pushed the changes so if you update SAM, it should hopefully work now.
Interesting take on letting game sounds bleed through. You're right, it's not super distracting.

**Comment by felleg** [comment]
Looks like it is working great now! For my own needs, this will suffice. Here I point out some slight instabilities / nitpicks, but thanks again for your great work!

- When trying to access the global volume setting via OSD, the sound frequently cuts
- When skipping a game via MiSTer_SAM_on.sh, the sound cuts

Other feedback: 
- The 80s playlist works fine, but seem to take precedence over the *.mp3 files I put in `/media/fat/music`. I can `rm 80s.pls` to fix this issue, but I fear this will initially confuse some users.

**Comment by mrchrisster** [comment]
Great, thanks for your feedback. I don't have mp3s in my music folder so that's great to know. I'll add some notes in the menu.

The sound cutting is because of core changes and the fpga reconfiguring. Unfortunately that is not something we can mitigate.
Not sure I understand your first feedback point. What exactly happens when accessing global volume?

**Comment by felleg** [comment]
> The sound cutting is because of core changes and the fpga reconfiguring. Unfortunately that is not something we can mitigate.

My bad, I wasn't being clear: I mean the sound cuts and stays cut, i.e. the music gets turned off permanently ;)

> Not sure I understand your first feedback point. What exactly happens when accessing global volume?

This means when I open the OSD, press left then up to reach the global volume setting, the music gets turned off apparently.

**Comment by mrchrisster** [comment]
Skip command should now not end bgm anymore. wizzo from the BGM project was nice enough to write some control feature for SAM. 
You can update BGM from SAM's menu, hopefully it works now. I can't replicate the OSD issue you are having.

**Comment by felleg** [comment]
Awesome work!! Thanks so much!

I can live with my issue of sound cutting. In particular, I will study the bgm.sh script more closely and create an issue if needed. 

Closing this issue.
